name: Publish to npm

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install
        working-directory: packages/jest_vendor

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: packages/jest_vendor/jest-lua.rbxm

      - name: Patch npm version
        run: npm version patch
        working-directory: packages/jest_vendor

      - name: Publish to npm
        run: echo npm publish
        working-directory: packages/jest_vendor
